[tool.briefcase]
project_name = "NURDS App"
bundle = "com.example"
version = "0.0.1"
url = "https://example.com/nurdsapp"
license = "BSD license"
author = 'Dallin Schiffman and Daniel Dennis'
author_email = "dtschiffman@gmail.com"

[tool.briefcase.app.nurdsapp]
formal_name = "NURDS App"
description = "Smartphone app for the New Universal Recreation Device System"
icon = "src/nurdsapp/resources/nurdsapp"
sources = ['src/nurdsapp']
requires = [
]


[tool.briefcase.app.nurdsapp.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.nurdsapp.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.nurdsapp.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.nurdsapp.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.nurdsapp.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.nurdsapp.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.nurdsapp.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.nurdsapp.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
